### ISSUE TITLE
Devkit Fails To Locate Registry Entry for Ruby 2.0.0 (64-bit) on Windows 7

### ISSUE THREAD

**Issue by greena13** [oneclick/rubyinstaller#178]
I have installed ruby 2.0.0p195 [x64-mingw32] on Windows 7 Ultimate, Service Pack 1 (64-bit) with no previous ruby or devkit versions installed. I then attempted to use the devkit installer DevKit-mingw64-64-4.7.2-20130224-1432-sfx.

I extracted the sfx to a directory without spaces and navigated the terminal to the root directory of the extracted files to run `ruby dk.rb init`. No ruby installations were detected.

I took a look at the dk.rb file and added 'Software\Wow6432Node\RubyInstaller\MRI' to the REG_KEYS array on line 12. The ruby installation was then detected when I ran `ruby dk.rb init` a second time and the installation proceded without error.

**Comment by rhyeal** [comment]
Running Windows 8.1 on a Macbook (via Bootcamp). I installed Ruby 2.1 x64 and the devkit. Init failed to detect any files.

I added 'Software\Wow6432Node\RubyInstaller\MRI' to the dk.rb file and it was able to detect the installation.

**Comment by Azolo** [comment]
Yeah, this is fixed as of #237 but there hasn't been a new DevKit released with the fix yet.

**Comment by wstaples** [comment]
Any update on this issue? It still appears to be happening with Windows Server 2012, Ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32], Devkit 4.7.2.

**Comment by brianrobertarmstrong** [comment]
Ran into this issue with chocolatey today. The discussion in #237 makes it clear that a new DevKit release is a big deal, so I went poking around.  
If I understand correctly, the root cause is that the Inno Setup installer is 32-bit, so its registry updates get redirected and aren't visible to `dk.rb init` running under 64-bit ruby.  
Could the `ArchitecturesInstallIn64BitMode=x64` [directive ](http://www.jrsoftware.org/ishelp/index.php?topic=setup_architecturesinstallin64bitmode) solve this problem? If the installer runs in 64-bit mode, then it should create the HKLM/HKCU keys in the location that the current version of DevKit is expecting.  
I plan to give it a try, but I don't know how long it will take me to get this thing building locally, so I figured I would throw the idea out there for everyone else.

**Comment by qwebek** [comment]
This is stll happening on windows 7 x64 and ruby231x64 and DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe, is there any workaround?
